# Generated by Django 3.0.5 on 2020-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
